apiVersion: apps/v1
kind: Deployment
metadata:
  name: persister-deployment
  namespace: trandoshan-io
  labels:
    app: persister
spec:
  replicas: 2
  selector:
    matchLabels:
      app: persister
  template:
    metadata:
      labels:
        app: persister
    spec:
      containers:
      - name: persister
        image: trandoshanio/persister
        env:
          - name: MONGO_URI
            value: mongodb://trandoshan:changeme$@database-mongodb:27017/trandoshan
          - name: NATS_URI
            value: nats://trandoshan:trandoshanPwd$@messaging-system-nats-client:4222
          - name: STORAGE_PATH
            value: /resources
          volumeMounts:
          - mountPath: /resources
            name: resources
      volumes:
      - name: resources
        persistentVolumeClaim:
          claimName: trandoshan-io-resources
