apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  namespace: trandoshan-io
  labels:
    app: crawler
spec:
  replicas: 15
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: trandoshanio/crawler