apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  namespace: trandoshan-io
  labels:
    app: crawler
spec:
  replicas: 15
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: trandoshanio/crawler
        env:
        - name: TOR_PROXY
          value: tor-proxy-service:9050
        - name: NATS_URI
          value: nats://trandoshan:trandoshanPwd$@messaging-system-nats-client:4222
        - name: FORBIDDEN_CONTENT_TYPES
          value: application/octet-stream
        - name: USER_AGENT
          value: trandoshan-io/crawler