apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: trandoshan-io
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: trandoshanio/api
        env:
        - name: MONGO_URI
          value: mongodb://trandoshan:changeme$@database-mongodb:27017/trandoshan
        ports:
        - containerPort: 8080